spring.application.name=fortpointproperties

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.zofbcpjnrfzyvbxwvunz
spring.datasource.password=azLigat0-102504!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect