spring.config.import=optional:file:.env[.properties]
spring.application.name=fortpointproperties

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate Configuration
#change to update later once we have the database schema set up
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.statement_cache.size=0

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000

supabase.url=${SUPABASE_URL}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
supabase.storage.bucket=career-resumes
supabase.article-bucket=article-cover-photos
supabase.storage.signed-url-expiration-seconds=300
